### ISSUE TITLE
Logrotete for the flex log file

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity-k8s#117]
1. Add log rotate to flex alpine image

2. Add log rotate config file for ubiqutiy and add it to the image during build
/mnt/flex/ibm~ubiquity-k8s-flex/ubiquity-k8s-flex.log {
    su root root
    size 50M
    daily
    rotate 5
    copytruncate 
    create 0600 root root
}

3. Trigger logrotate as part of the setup_flex.sh script that run in the Flex daemonset. The logrotate should run every 24hours.
4. tail -f on the ubiquity log file as part of the setup_flex.sh, so it will be visible via the kubectl logs command on the flex POD.

**How to test**
1. make sure you can see the logs by kubectl logs <flex pod1>,   kubectl logs <flex pod2>, ....
make sure the logs are for the right flex node. 
For the host node, the flex log path is: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ubiquity-k8s-flex/ubiquity-k8s-flex.log
For the Pod, the flex log path is: /mnt/flex/ibm~ubiquity-k8s-flex/ubiquity-k8s-flex.log

2. Make sure the flex logs both on the host and POD, is actually rotate every 24 hours if it pass the 50MB. 

3. Make sure if there is 5 rotated log files exist, the oldest log file will be deleted while rotating the 6th time

4. After rotate, please make sure the log will still write into ubiquity-k8s-flex.log.

5. Please make sure there is no logs missing while doing logrotate.

6. make sure that everything still working for the long run (you can still see the logs in kubectl logs all the time, and the logrotate is doing well all the time.)

**Comment by shay-berman** [comment]
@hfeish  What is the status of this ticket?

**Comment by hfeish** [comment]
Tested pass, and had pulled a request to you and lior to review.
IBM/ubiquity-k8s#120

**Comment by shay-berman** [comment]
@hfeish  please update the ticket status (Zenhub)

**Comment by hfeish** [comment]
Test passed https://jira.xiv.ibm.com/browse/UB-448
