### ISSUE TITLE
Add support for K8s 1.6

### ISSUE THREAD

**Issue by midoblgsm** [IBM/ubiquity-k8s#15]
k8s v1.6.x comes with a new Flex API. As a use I should be able to attach volumes when I am using k8s v 1.6.x
The new API is:
<driver executable> getvolumename <json options>
<driver executable> attach <json options> <node name>
<driver executable> detach <mount device> <node name>
<driver executable> waitforattach <mount device> <json options>
<driver executable> isattached <json options> <node name>
<driver executable> mountdevice <mount dir> <mount device> <json options> 
<driver executable> unmountdevice <mount device>
<driver executable> mount <mount dir> <json options>
<driver executable> unmount <mount dir>

The structure of the response expected by Kubelet:
{         
"status": "<Success/Failure/Not supported>",         
"message": "<Reason for success/failure>",         
"device": "Path to the device attached. valid only for attach & waitforattach call-outs”         
"volumeName": "Cluster wide unique name of the volume”
"attached": True/False}

**Comment by shay-berman** [comment]
@midoblgsm  i think you should move this ticket to waiting for testing. since u finish it
