### ISSUE TITLE
rename provisioner and flex conf file and binary file - UX improvement 

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity-k8s#50]
We need to change the conf and binary according to the changes in the new README files #41.
Please apply the change directly to branch https://github.com/IBM/ubiquity-k8s/tree/feature/README_file_align_for_POC, which currently has the updated README files but with out file name changes in the code.

Here is a summary of the changes that need to be done.
1. Provisioner binary file and service name should be named **ubiquity-k8s-provisioner** instead of just "provisioner"
2.provisioner conf file, should be named **ubiquity-k8s-provisioner.conf** instead of just "ubiquity-client.conf" and it must locate in **/etc/ubiquity/**
3. the flex volume should be named **ubiquity-k8s-flex** instead of just "ubiquity" (which confusing if the ubiquity server locate on the same node)
4. the flex conf file should be named **ubiquity-k8s-flex.conf**, instead of ubiqutiy-client.conf and its now by default should be locate in **/etc/ubiquity**

after merge it to dev, we must adjust also the CI to use the new name conversions.

Additional changed added during this task:
1. rename also the log files : ubiquity-k8s-flex.log and ubiquity-k8s-provisioner.log
2. use ubiquity-k8s-provisioner in the provisioner_ID and also in the createdby params of the PV (can be viewed by kubectl get pv -o json)

**Comment by shay-berman** [comment]
@midoblgsm, two comments : 
1. why the ubiquity-k8s-provisioner.service needs to start only after docker service and also why it "requires" it?   these lines:
```
After=docker.service
Requires=docker.service
```

2. about the kubernetes.conf file that the provision uses to listen to PVCs requests.
about the file name and its location. I would like the default to be: /etc/ubiquity/k8s.conf   and expecting the customer to generate this file in this location and with this name.  
Do you agree?

**Comment by YuDaiWang** [comment]
it is fixed, I verified it on v1.5.6, the new name works well and flexvolume log is in ubiquity-k8s-flex.log now

**Comment by shay-berman** [comment]
@midoblgsm , @YuDaiWang 
1. I found that we have a bug in the k8s log name, in the main file its name was still the old one ubiquity-provisioner.log so I fixed it.

2. In addition i saw the old name also in the details of the PV (while running kubectl get pv -o json) as the provisioner_ID and k8s.io/createdby. So I fixed it as well.

@midoblgsm  please review and approve the PR

**Comment by shay-berman** [comment]
@YuDaiWang  please check that the provisioner log is ok after my last fix.  and if so please close this ticket.
thanks

**Comment by YuDaiWang** [comment]
The provisioner log is in ubiquity-k8s-provisioner.log now. 
As I configure, the log is in /tmp/ubiquity/, under this folder there is a file named "k8sresources.UbiquityProvisionerName.identity", I think it is better to rename it to "ubiquity-k8s-provisioner.identity".
Under folder /tmp, there are ubiquity-k8s-provisioner related logs, how about moving these logs also to folder /tmp/ubiquity/ that configured for provisioner.
