### ISSUE TITLE
Problem with ubiquity-provisioner service in CfC deployment

### ISSUE THREAD

**Issue by cwesthues** [IBM/ubiquity-k8s#51]
Dear all,

I have an issue with ubiquity-k8s; ubiquity service runs nice (uniquity-docker as well),
but ubiquity-provisioner service fails ;=(
Here is the output of journalctl:
...
Aug 11 10:32:12 worker1.ibm.edu provisioner[21021]: F0811 10:32:12.107513   21021 semver.go:47] failed to parse semver from
gitversion "cfc-1.6.1.17+f04cb2d1cde1c7-dirty": Invalid character(s) found in major number "cfc-1"
...
Here is the (manual) output of https://127.0.0.1:8001/version
{
  "major": "1",
  "minor": "6",
  "gitVersion": "cfc-1.6.1.17+f04cb2d1cde1c7-dirty",
  "gitCommit": "f04cb2d1cde1c7ae8edbb44289529b871e84d541",
  "gitTreeState": "dirty",
  "buildDate": "2017-04-18T07:25:14Z",
  "goVersion": "go1.8",
  "compiler": "gc",
  "platform": "linux/amd64"
}

Any idea? Is the "-" in "cfc-1" an issue?

Thanks in advance,

Christof

**Comment by midoblgsm** [comment]
@cwesthues ,
the issues comes from "cfc-1.6.1.17+f04cb2d1cde1c7-dirty" git version that is not parsable by kuberenetes version parser. A workaround is to hard-code the version in:
https://github.com/IBM/ubiquity-k8s/blob/dev/cmd/provisioner/main/main.go#L111
to "v1.6.1" . Should you do that please comment out these lines as well: https://github.com/IBM/ubiquity-k8s/blob/dev/cmd/provisioner/main/main.go#L91-L94

**Comment by midoblgsm** [comment]
@cwesthues please open an issue on cfc repo to resolve this issue.
Thanks

**Comment by shay-berman** [comment]
can we resolve it in ubiquity?

does it mean that cfc will not work until this fix will take place?

בתאריך 11 באוג׳ 2017 09:17 PM,‏ "Mohamed Mohamed" <notifications@github.com>
כתב:

**Comment by midoblgsm** [comment]
@shay-berman I think that this is not an issue for ubiquity-k8s, but we can add another check, if the original git version fails we use a static one like "v1.6.1" or later ... but if this issue is resolved from cfc side, we don't need to do anything

**Comment by macthev** [comment]
It doesn't like the hyphen for patch.
ie
this works 
v1.6.1-dirty
but not this
v1.6.1.dirty

**Comment by shay-berman** [comment]
@macthev  \ @midoblgsm , can we close this issue ?  (since its its CfC issue and not ubiquity)

**Comment by macthev** [comment]
An override would help. Otherwise okay to close from me.

**Comment by shay-berman** [comment]
@macthev  do you know if there is an open issue in CfC about fixing the CfC version number?

**Comment by macthev** [comment]
I dont think so.

**Comment by k82cn** [comment]
I don-t think this's a ICP/CfC issue; ubiquity-provisioner should not only bind to k8s community version, it's better to be friendly to other distribution.

**Comment by shay-berman** [comment]
ubiquity provisioner communicates with the k8s API server.
The fail not cause by ubiquity, the kuberenetes version parser fails to parse the cfc version number since its not standard for k8s parser.

@macthev please confirm that CfC plan to fix this.

@k82cn, any suggestions?

**Comment by k82cn** [comment]
Maybe a warning/error message is enough for end user instead of panic.

**Comment by macthev** [comment]
Yes that would be sufficient or and override.

**Comment by k82cn** [comment]
just replace `panic` with `logger.Printf` :).

**Comment by shay-berman** [comment]
Per Matthew Levan, its no longer issue with the latest ICP installation.
So I am closing this ticket.
