### ISSUE TITLE
GPFS: Unable to mount volumes for pod

### ISSUE THREAD

**Issue by cwesthues** [IBM/ubiquity-k8s#56]
Dear all,

I got stuck in mounting a simple volume to a pod, here is the full message:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  8m		8m		1	default-scheduler			Normal		Scheduled	Successfully assigned default-nginx-with-ubiquity-nginx-with-ubiquity-4248045469xxt70 to 192.168.0.12
  6m		2m		3	kubelet, 192.168.0.12			Warning		FailedMount	Unable to mount volumes for pod "default-nginx-with-ubiquity-nginx-with-ubiquity-4248045469xxt70_default(abf79c0f-8343-11e7-b3b4-000c29000001)": timeout expired waiting for volumes to attach/mount for pod "default"/"default-nginx-with-ubiquity-nginx-with-ubiquity-4248045469xxt70". list of unattached/unmounted volumes=[persistdir]
  6m		2m		3	kubelet, 192.168.0.12			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"default-nginx-with-ubiquity-nginx-with-ubiquity-4248045469xxt70". list of unattached/unmounted volumes=[persistdir]

I put some additional screenshots to https://ibm.box.com/s/gtho78nrezkdwymrn1k0g63xm6ja6865

I also did:
mmlinkfileset  gpfs pvc-0ced5a5a-8343-11e7-b3b4-000c29000001 -J /mnt/gpfs/test123

Any idea where to look deeper now? ubiquity and ubiquity-provisioner services are running
without issues, and I can't see anything weired in the log files.

Thanks in advance,

Christof

**Comment by midoblgsm** [comment]
Hi @cwesthues , can you paste the log from the flex volume plugin? We can figure out if the call was passed to flex or not.

**Comment by cwesthues** [comment]
Hi there,

unfortunatelly there is nothing new in the logs on the node the pod was assigned to. I used your
original example in deploy/pod.yml:

[root@cpmaster deploy]# more pod.yml 
kind: Pod
apiVersion: v1
metadata:
  name: write-pod-test
spec:
  containers:
  - name: write-pod
    image: midoblgsm/kubenode
    volumeMounts:
      - name: ubiquity-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: ubiquity-pvc
      persistentVolumeClaim:
        claimName: ubiquity-claim-fileset
[root@cpmaster deploy]# 


kubectl create -f pod.yml
[root@cpmaster deploy]# kubectl describe pod write-pod-test
Name:		write-pod-test
Namespace:	default
Node:		192.168.0.12/192.168.0.12
Start Time:	Thu, 24 Aug 2017 17:09:39 +0200
Labels:		<none>
Annotations:	<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  write-pod:
    Container ID:	
    Image:		midoblgsm/kubenode
    Image ID:		
    Port:		
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /mnt from ubiquity-pvc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f1bb0 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  ubiquity-pvc:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	ubiquity-claim-fileset
    ReadOnly:	false
  default-token-f1bb0:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-f1bb0
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  5m		5m		1	default-scheduler			Normal		Scheduled	Successfully assigned write-pod-test to 192.168.0.12
  3m		1m		2	kubelet, 192.168.0.12			Warning		FailedMount	Unable to mount volumes for pod "write-pod-test_default(406f265b-88de-11e7-9fa4-000c29000001)": timeout expired waiting for volumes to attach/mount for pod "default"/"write-pod-test". list of unattached/unmounted volumes=[ubiquity-pvc]
  3m		1m		2	kubelet, 192.168.0.12			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"write-pod-test". list of unattached/unmounted volumes=[ubiquity-pvc]
[root@cpmaster deploy]# 

Here is the output of `docker volume list`:
DRIVER              VOLUME NAME
local               2237f299ca2426750583453d8f64160bc3dee301221bc71b3e62ed628289b76d
local               3e7c59409cd6475f0a062ac4f83bd854f82073bcd0e0611d92c523a13ebf0623
ubiquity            pvc-599241e8-88c5-11e7-9fa4-000c29000001


Just FYI, when I use a (modified) flex_smoke_test.sh, it works nice:
[root@cpmaster scripts]# more flex_smoke_test.sh
#!/bin/sh
. /root/.bashrc 
FILESET="testvolume"
FILESYSTEM=gold
scripts=$(dirname $0)
cd $scripts/../bin
#Just in case we cleanup
mmdelfileset ${FILESYSTEM} ${FILESET} -f 2>/dev/null >/dev/null
docker volume rm ${FILESET} 2>/dev/null >/dev/null
printf "\n calling ubiquity init\n"
./ubiquity init
printf "\n docker volume create\n"
docker volume create --driver ubiquity --name ${FILESET} --opt size=1 --opt profile=${FILESYSTEM}
printf "\n calling ubiquity mount\n"
mkdir -p /tmp/dir1
./ubiquity mount /tmp/dir1/${FILESET} ${FILESET} \{\"device\"\:\"\"\}
printf "\n calling touch /tmp/dir1/${FILESET}/abcde\n"
touch /tmp/dir1/${FILESET}/abcde
printf "\n calling ubiquity unmount\n"
./ubiquity unmount /mnt/gpfs/${FILESET}
rm -rf /tmp/dir1
printf "\n calling ubiquity detach\n"
./ubiquity detach ${FILESET}
printf "\n calling ls -al /mnt/gpfs/${FILESET}\n"
ls -al /mnt/gpfs/${FILESET}
printf "\n calling docker volume rm\n"
docker volume rm ${FILESET}
printf "\n calling mmunlinkfileset\n"
mmunlinkfileset ${FILESYSTEM} ${FILESET}
printf "\n calling mmdelfileset\n"
mmdelfileset ${FILESYSTEM} ${FILESET} -f



Here is the output of that script:

[root@cpmaster scripts]# ./flex_smoke_test.sh

 calling ubiquity init
{"status":"Success","message":"Plugin init successfully","device":""}
 docker volume create
testvolume

 calling ubiquity mount
{"status":"Success","message":"Volume mounted successfully to /mnt/gpfs/testvolume","device":""}
 calling touch /tmp/dir1/testvolume/abcde

 calling ubiquity unmount
{"status":"Success","message":"Volume unmounted successfully","device":""}
 calling ubiquity detach
{"status":"Success","message":"Volume detached successfully","device":"testvolume"}
 calling ls -al /mnt/gpfs/testvolume
total 256
drwxrwxrwx 2 root root   4096 Aug 24 17:24 .
drwxr-xr-x 3 root root 262144 Aug 24 17:24 ..
-rw-r--r-- 1 root root      0 Aug 24 17:24 abcde

 calling docker volume rm
testvolume

 calling mmunlinkfileset
Fileset testvolume was unlinked.

 calling mmdelfileset
Checking fileset ...
Checking fileset complete.
Deleting user files ...
 100.00 % complete on Thu Aug 24 17:24:55 2017  (     67584 inodes with total        264 MB data processed)
Deleting fileset ...
Fileset testvolume deleted.
[root@cpmaster scripts]# 


Thanks in advance,

Christof

**Comment by cwesthues** [comment]
Hi Mohamed,

somewhere in the doc it says "flex needs kubernetes 1.5.2, 1.6.X will not work".
So I went back from cfc-1.2.0 to cfc-1.1.0, which runs on 1.5.2, but no change of
behaviour ;=(

**Comment by shay-berman** [comment]
@midoblgsm  is this issue relevant? if not please close.  I tag this issue as Spectrum scale backend.

**Comment by shay-berman** [comment]
@aswarke  is it still relevant?

**Comment by cwesthues** [comment]
Dear all,
 
I'm currently NOT working on this one any longer,
you can close this one...
 
Thanks,
 
Christof
Christof Westhues
IBM Storage Solutions Technical SME PPP
Phone: +49 173 6413918
E-mail: cwesthues@de.ibm.com
 
 
----- Ursprüngliche Nachricht -----Von: shay-berman <notifications@github.com>An: IBM/ubiquity-k8s <ubiquity-k8s@noreply.github.com>CC: cwesthues <cwesthues@de.ibm.com>, Mention <mention@noreply.github.com>Betreff: Re: [IBM/ubiquity-k8s] GPFS: Unable to mount volumes for pod (#56)Datum: So, 25. Mär 2018 15:08 
@aswarke is it still relevant?

**Comment by shay-berman** [comment]
closing per @cwesthues respond
