### ISSUE TITLE
change PV name

### ISSUE THREAD

**Issue by midoblgsm** [IBM/ubiquity-k8s#64]
- Use labels in PVC volumeName
- in the provisioner change options.PVName to this label

**Comment by shay-berman** [comment]
we have some options here to discuss
1. set pv name by the pvc name
2. set pv name only by a label.name set in the pvc
3. set pv name as the pvcid

in addtion we should consider namespace in pv name.   since pv is not namespace  it doesnt make sense to add it to the pv name.

**Comment by shay-berman** [comment]
this issue was already done by Lior
