### ISSUE TITLE
GPFS : param filesystem and fileset are required opts for using lightweight volumes

### ISSUE THREAD

**Issue by macthev** [IBM/ubiquity-k8s#84]
Error in validate params: 'filesystem' and 'fileset' are required opts for using lightweight volumes
In "storage_class_lightweight.yml"
Is fileset missing?

parameters:
  filesystem: "gold"
  backend: "spectrum-scale"
type: "lightweight"

**Comment by macthev** [comment]
added fileset:"test"
now fails
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:163: Opts for create: map[string]interface {}{"type":"lightweight", "backend":"spectrum-scale", "fileset":"test", "filesystem":"fs1", "quota":"1024M", "size":"1"}
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:169: Trying to determine type for request
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:714: determineTypeFromRequest start
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:729: determineTypeFromRequest end
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:175: Volume type requested: lightweight
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:733: validateAndParseParams start
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:714: determineTypeFromRequest start
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:729: determineTypeFromRequest end
ubiquity: 2017/09/23 17:33:02 spectrumscale.go:784: 'quota' is not supported for lightweight volumes

**Comment by macthev** [comment]
fixed:  added fileset: "test" and set 'storage:  'to no value  in pvc_lightweight template

**Comment by macthev** [comment]
Please update template.  
storage_class_light_lightweight : add fileset option
pvc_lightweight:   set storage:  instead of 1Gi to prevent sending quota param.

**Comment by shay-berman** [comment]
@aswarke is this issue still relevant? if not please close.  meanwhile i tag it to be related to GPFS backend in ubiquity.

**Comment by shay-berman** [comment]
@aswarke is this issue still relevant? if not please close.

**Comment by yadaven** [comment]
We are not supporting Lightweight volumes. So closing this issue.
