### ISSUE TITLE
PVC not being created when only using StorageClassName

### ISSUE THREAD

**Issue by matt-levan** [IBM/ubiquity-k8s#97]
Ubiquity will successfully create a PersistentVolume from a PersistentVolumeClaim when the following yaml file is used. In this yaml file we are using a metadata:annotations:volume.beta.kubernetes.io/storage-class: "ibmc-block-gold".

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "tengvolumeclaim-ibmc-block-gold-2"
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-block-gold"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

```
Log output from ubiquity-k8s-provisioner:
ERROR: logging before flag.Parse: I1011 12:55:57.352179       1 controller.go:846] scheduleOperation[lock-provision-default/tengvolumeclaim-ibmc-block-gold-2[86322113-ae83-11e7-a39e-005056973966]]
ERROR: logging before flag.Parse: I1011 12:55:57.367094       1 controller.go:846] scheduleOperation[lock-provision-default/tengvolumeclaim-ibmc-block-gold-2[86322113-ae83-11e7-a39e-005056973966]]
ERROR: logging before flag.Parse: I1011 12:55:57.385943       1 leaderelection.go:157] attempting to acquire leader lease...
ERROR: logging before flag.Parse: I1011 12:55:57.394922       1 leaderelection.go:179] sucessfully acquired lease to provision for pvc default/tengvolumeclaim-ibmc-block-gold-2
ERROR: logging before flag.Parse: I1011 12:55:57.395120       1 controller.go:846] scheduleOperation[provision-default/tengvolumeclaim-ibmc-block-gold-2[86322113-ae83-11e7-a39e-005056973966]]
PVC with capacity 10737418240ubiquity-k8s-provisioner: 2017/10/11 12:55:57 client.go:71: remoteClient: create start
ubiquity-k8s-provisioner: 2017/10/11 12:55:58 client.go:94: remoteClient: create end
ubiquity-k8s-provisioner: 2017/10/11 12:55:58 client.go:148: remoteClient: GetVolumeConfig start
ERROR: logging before flag.Parse: I1011 12:55:58.887439       1 controller.go:583] volume "pvc-86322113-ae83-11e7-a39e-005056973966" for claim "default/tengvolumeclaim-ibmc-block-gold-2" created
ubiquity-k8s-provisioner: 2017/10/11 12:55:58 client.go:171: remoteClient: GetVolumeConfig finish
ERROR: logging before flag.Parse: I1011 12:55:58.893073       1 controller.go:596] volume "pvc-86322113-ae83-11e7-a39e-005056973966" for claim "default/tengvolumeclaim-ibmc-block-gold-2" saved
ERROR: logging before flag.Parse: I1011 12:55:58.893114       1 controller.go:632] volume "pvc-86322113-ae83-11e7-a39e-005056973966" provisioned for claim "default/tengvolumeclaim-ibmc-block-gold-2"
ERROR: logging before flag.Parse: I1011 12:55:59.404456       1 leaderelection.go:199] stopped trying to renew lease to provision for pvc default/tengvolumeclaim-ibmc-block-gold-2, task succeeded

> \# kubectl describe pvc/tengvolumeclaim-ibmc-block-gold-2
> Name:		tengvolumeclaim-ibmc-block-gold-2
> Namespace:	default
> StorageClass:	ibmc-block-gold
> Status:		Bound
> Volume:		pvc-86322113-ae83-11e7-a39e-005056973966
> Labels:		<none>
> Annotations:	control-plane.alpha.kubernetes.io/leader={"holderIdentity":"3b6f664f-adfc-11e7-872e-92235e9d2e07","leaseDurationSeconds":15,"acquireTime":"2017-10-11T12:55:57Z","renewTime":"2017-10-11T12:55:59Z","lea...
> 		pv.kubernetes.io/bind-completed=yes
> 		pv.kubernetes.io/bound-by-controller=yes
> 		volume.beta.kubernetes.io/storage-class=ibmc-block-gold
> 		volume.beta.kubernetes.io/storage-provisioner=ubiquity/flex
> Capacity:	10Gi
> Access Modes:	RWO
> Events:
>   FirstSeen	LastSeen	Count	From												SubObjectPath	Type		Reason			Message
>   ---------	--------	-----	----												-------------	--------	------			-------
>   1m		1m		2	persistentvolume-controller											Normal		ExternalProvisioning	waiting for a volume to be created, either by external provisioner "ubiquity/flex" or manually created by system administrator
>   1m		1m		1	ubiquity/flex ubiquity-k8s-provisioner-2638031318-hjd5n 3b6f664f-adfc-11e7-872e-92235e9d2e07			Normal		ProvisioningSucceeded	Successfully provisioned volume pvc-86322113-ae83-11e7-a39e-005056973966

Per the kubernetes blog we should be able to use a Spec:storageClassName: ibmc-block-gold as detailed in the yaml below, instead of the annotation to create a PersistentVolume from a PersistentVolumeClaim, but this currently fails.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "tengvolumeclaim-ibmc-block-gold-2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-block-gold

```
Log output from ubiquity-k8s-provisioner:
ERROR: logging before flag.Parse: E1011 12:49:20.059701       1 controller.go:414] Claim "default/tengvolumeclaim-ibmc-block-gold-2": StorageClass "" not found
ERROR: logging before flag.Parse: E1011 12:49:20.069513       1 controller.go:414] Claim "default/tengvolumeclaim-ibmc-block-gold-2": StorageClass "" not found

> \# kubectl describe pvc/tengvolumeclaim-ibmc-block-gold-2
> Name:		tengvolumeclaim-ibmc-block-gold-2
> Namespace:	default
> StorageClass:	ibmc-block-gold
> Status:		Pending
> Volume:		
> Labels:		<none>
> Annotations:	volume.beta.kubernetes.io/storage-provisioner=ubiquity/flex
> Capacity:	
> Access Modes:	
> Events:
>   FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
>   ---------	--------	-----	----				-------------	--------	------			-------
>   1m		7s		7	persistentvolume-controller			Normal		ExternalProvisioning	waiting for a volume to be created, either by external provisioner "ubiquity/flex" or manually created by system administrator
> 

We are testing this on the following version of kubernetes: v1.7.3-7+154699da4767fd.

**Comment by shay-berman** [comment]
Hi @matt-levan 

Mohamed fixed it and I also aligned the scbe acceptance test and "ubiquity_deployment.sh -a sanity" to use the new convension of StorageClassName instead of the annotations(#101). And it passed acceptance test OK.

Please retest it (its all in dev now) and lets us know if we can close this ticket.

Thanks

**Comment by matt-levan** [comment]
I have tested and this ticket can be closed.

**Comment by shay-berman** [comment]
Thanks @matt-levan

This issue solved in the dev branch.

Great WW collaboration

closing this ticket.
